server:
  port: 8080
  context-path: /

management:
  context-path: /status

info:
  build:
    name: ${name}
    group: ${group}
    description: ${description}
    version: ${version}

spring:
  data:
    mongodb:
      uri: mongodb://35.165.164.112:27017/oswbmc_db